### ISSUE TITLE
LICENSE file misspelled

### ISSUE THREAD

**Issue by liuhao-ibm** [joho/godotenv#78]

**Comment by breml** [comment]
I stumbled over this issue today as well, because our automatic license checker fails to recognize the license for this package. So I would appreciate, if this could be fixed.

**Comment by henhouse** [comment]
"Licence" is the correct spelling in British-English for the noun. GitHub recognizes both interchangeably. American English tends to dominate the nomenclature for these things (e.g.: `Authorization` header instead of `Authorisation`), so perhaps it's best to change it.

Can your license checker be modified to recognize both?

**Comment by breml** [comment]
I use [wwhrd](https://github.com/frapposelli/wwhrd), which then uses [go-license](https://github.com/ryanuber/go-license/). I just found, that `go-license` already supports the British spelling, but the dependency has not yet been updated in `wwhrd`. I have filed an issue there as well (https://github.com/frapposelli/wwhrd/issues/25).

**Comment by breml** [comment]
`wwhrd` has been updated in https://github.com/frapposelli/wwhrd/pull/26. That resolves the problem for me. As far as I am concerned, this issue can be closed (but I am not the original author, ping @liuhao-ibm).
